name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm i # change this to npm ci after you start a project
      - name: Run tests
        run: npm run build
