name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  prettier:
    uses: ./.github/workflows/prettier.yml
  unit-tests:
    uses: ./.github/workflows/unit_tests.yml
